### ISSUE TITLE
vikunja logo

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/vikunja#60]
![vikunja_logo](https://user-images.githubusercontent.com/10682583/146919330-b254b7bb-7ffd-4377-8c23-6cf828986187.png)

**Comment by SimeonEhrig** [comment]
A new smoothed version. Thanks to Hannes for the Inkscape training.

![vikunja_logo2](https://user-images.githubusercontent.com/10682583/146938302-46a01ac8-2073-4bd3-ae4e-d2444a1913a3.png)

**Comment by SimeonEhrig** [comment]
Rounded ears
![vikunja_logo3](https://user-images.githubusercontent.com/10682583/146943090-2fe0ed96-118c-41e0-9690-2204385be075.png)

**Comment by bussmann** [comment]
Can you do a better font?

**Comment by SimeonEhrig** [comment]
Yes an no. I'm able to change the font but I'm not sure what is better :sweat_smile: 
I copied the font from the alpaka logo.

**Comment by sliwowitz** [comment]
I think using the same font for both alpaka and vikunja logos is a good idea. But it does feel a liitle bit off here. I'd try decrease the kerning - maybe except between v and i, and between n andj j which seem rather packed.

**Comment by SimeonEhrig** [comment]
Because I'm lazy, I tried the font of the llama logo (I like .svg, they are totally open source :grin: )
![vikunja_logo](https://user-images.githubusercontent.com/10682583/147060622-2e9713bc-0ff7-4ff4-98f5-094a3f97b811.png)

I think, that's looks better.

**Comment by SimeonEhrig** [comment]
Some ideas form @sliwowitz 
![vikunja_logo_without_ear](https://user-images.githubusercontent.com/10682583/147082735-41fd9f8c-2809-46dc-bdba-8cb406da3634.png)

![vikunja_logo_without_front_neck](https://user-images.githubusercontent.com/10682583/147082752-c53bfa21-ff78-4685-8672-309d69f1708c.png)

![vikunja_logo_without_front_neck_ear](https://user-images.githubusercontent.com/10682583/147082765-1cc67351-3fb5-4da2-b750-1f21a6f683e4.png)

**Comment by j-stephan** [comment]
The last version is awesome!

**Comment by SimeonEhrig** [comment]
I prefer the second last version (open neck, two ears). Let's see, what the other means. But I think, one of the last 4 versions could be the final.

**Comment by psychocoderHPC** [comment]
I prefer the second one with two ears too.

**Comment by SimeonEhrig** [comment]
> I prefer the second one with two ears too.

I believe there is a miss understatement. There are 4 final version, split in 2 comments:

https://github.com/alpaka-group/vikunja/issues/60#issuecomment-999379129
1. closed neck and two ears

https://github.com/alpaka-group/vikunja/issues/60#issuecomment-999484573
2. close neck and one ear
3. open neck and two ears
4. open neck and one ear

I think, you mean version 3.

**Comment by psychocoderHPC** [comment]
I mean `3. open neck and two ears`

**Comment by bernhardmgruber** [comment]
I prefer the last two ones as well (non-closed path for the head). I slighly lean to the second last.

**Comment by SimeonEhrig** [comment]
Version 3 has won. It is part of PR #59
