### ISSUE TITLE
Make logo indepent of font's installed on the system

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/vikunja#74]
At the moment, the logo requires that the correct font is installed. Otherwise another font is used and the logo is broken.

fix: https://stackoverflow.com/questions/27381239/embedding-fonts-in-inkscape

**Comment by sliwowitz** [comment]
Don't do that, it can still lead to inconsistent display results. Convert the text to path instead with Path -> Object to Path

**Comment by SimeonEhrig** [comment]
> Don't do that, it can still lead to inconsistent display results. Convert the text to path instead with Path -> Object to Path (in Inkscape)

I changed the heading. The is actual the idea, which I want to do.
